config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  resources :users
  
  resources :resources do
    resources :comments, only: [:create, :destroy]
  end
  
  root 'static_pages#home'
  get  'static_pages/help'
  get  'static_pages/about'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :resources
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :resource
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :resource_id, presence: true
  validates :user_id, presence: true
  validates :content, presence: true
  validates :rating, presence: true
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  enum names: [ "Legal", "Accounting", "Sales", "Marketing", "Human Resources", "Venture Capital", "Industry Leads", "Security and Compliance", "UI and UX Design", "Technology Development" ]
  has_many :comments, dependent: :destroy
  belongs_to :user
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  #Is this the best email regex to use? Doesn't stop ..
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :category_id, presence: true
  validates :email, presence: true

  def average_rating
    if self.comments.size > 1
      self.comments.average(:rating).round(1)
    elsif self.comments.size == 1
      self.comments.average(:rating)
    else
       'undefined'
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  has_many :resources
  has_many :comments
  validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @resource = Resource.find(params[:resource_id])
    @comment = @resource.comments.create(comment_params)
    @user = @comment.user_id
    redirect_to resource_path(@resource)
  end
  
  def destroy
  end

    private

      def comment_params
        params.require(:comment).permit(:content, :rating, :user_id)
      end
  
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  def show
    @resource = Resource.find(params[:id])
    @category_id = @resource.category_id
    @category_name = Resource.names.key(@category_id)
    @comments = @resource.comments.all
    @num_comments = @resource.comments.count
  end
  
  def index
    @category_id = params[:category].to_i
    @category_name = Resource.names.key(@category_id)
    @resources = Resource.where("category_id = ?", @category_id)
  end

  def new
    @category_id = params[:category].to_i
    @category_name = Resource.names.key(@category_id)
    @resource = Resource.new
  end

  def create
    @resource = Resource.create(resource_params)
    if @resource.save
      redirect_to @resource
    else
      render 'new'
    end
  end

  private

    def resource_params
      params.require(:resource).permit(:name, :email, :position, :location, :company, :website, :category_id, :photo)
    end
     
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    @categories = Resource.names
    @comments = Comment.order("created_at desc").limit(5)
  end
  
  def help
  end
  
  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @comments = @user.comments.all
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="underline">
<li id="comment-<%= comment.id %> ">
  <!-- <%= link_to comment.resource.name, comment.resource %> -->
   <%= comment.content %>
   <br />
   <% @user = current_user %>
   Rating: <%= comment.rating %> stars
   <br />
   User: <%= comment.user.name %>
</li>
</div>

app/views/comments/new.html.erb
<h1>Comment</h1>

<%= @resource.inspect %>

<div>
  <%= form_for @comment, url: {action: "create" } do |f| %>

  <%= f.label :Comment %>
  <%= f.text_field :content %>
  <br />

  <%= f.label :Rating %>
  <%= radio_button :comment, :rating, 1 %>
  <%= radio_button :comment, :rating, 2 %>
  <%= radio_button :comment, :rating, 3 %>
  <%= radio_button :comment, :rating, 4 %>
  <%= radio_button :comment, :rating, 5 %>
  <br />  

  <%= @resource_id %>
  <%= f.hidden_field :resource_id, :value =>  @resource_id %>
  <!-- Submits correct resource with form -->

  <%= @user_id %>
  <%= f.hidden_field :user_id :value => @user.id %>
  
  <%= f.submit "Comment" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | BluePrintDirectory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-fixed-top">
    <div class="container">
      <%= link_to image_tag("bp_logo.png", alt: "Blueprint Health logo"), root_url, class: "navbar-left" %>
      <% if logged_in? %>
      <div class="dropdown navbar-right">
	<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
	   <%= current_user.name %>
	   <span class="caret"></span>
	 </button>
	<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
	   <li><%= link_to "Profile", current_user %></li>
	   <li><%= link_to "Log out", logout_path, method: :delete %></li>
	   </ul>
	</div>
      <% else %>
      <%= link_to " Login ", login_path, class: "navbar-right" %>
      <span class="navbar-right">|</span>
      <%= link_to " Sign Up ", 'users/new', class: "navbar-right" %>
      <% end %>
    </div>
  </header>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/resources/index.html.erb
<% provide(:title, @category_name) %>

<div class="category_names">
  <%= link_to @category_name, resources_path(:category => @category_id) %>
</div>

<div class="resource-link pull-right">
<%= link_to new_resource_path(:category => @category_id) do %>
<%= image_tag("plus.png", size:"20") %>Create a New <%= @category_name %> Resource
<% end %>
</div>

<table width='100%'>
    <% @resources.each do |resource| %>
    <tr class="bottom-border">
    <td class="space" width="25%"><%= link_to resource.name, resource %></td>
    <td class="space" width="25%"><%= resource.email %></td>
    <td class="space">
    <% if resource.average_rating != "undefined" %>
    Average Rating: <%= resource.average_rating %> stars
    <% else %>
    Be the first to rate <%= resource.name %>
    <% end %>
    </td>
  </tr>
  <% end %>
</table>

app/views/resources/new.html.erb
<% provide(:title, @category_name) %>

<div class="category_names">
  <%= link_to @category_name, resources_path(:category => @category_id) %>
</div>

<div class="resource-info">
  <%= form_for @resource, url: { action: "create" } do |f| %>
  <div class="pull-left">
  <div class="form-field">
    <%= f.label :name, "Name*" %>
    <%= f.text_field :name, :required => true,  class: 'form-control' %>
  </div>
  <div class="form-field">
  <%= f.label :position, "Position*" %>
  <%= f.text_field :position,  :required => true,  class: 'form-control' %>
  </div>
  <div class="form-field">
    <%= f.label :email, "Email*" %>
    <%= f.email_field :email, :required => true,  class: 'form-control' %>
  </div>
  </div>
  <div class="right">
   <div class="form-field">
  <%= f.label :location %>
  <%= f.text_field :location,  class: 'form-control' %>
   </div>
  <div class="form-field">
  <%= f.label :company %>
  <%= f.text_field :company,  class: 'form-control' %>
  </div>
  <div class="form-field">
  <%= f.label :website %>
  <%= f.text_field :website,  class: 'form-control' %>
  </div>
  <div class="form-field">
    <%= f.label :photo, "Image Link" %>
    <%= f.text_field :photo, class: 'form-control' %>
  </div>
  </div>


  <%= f.hidden_field :category_id, :value => @category_id %>
  <!-- Submits correct category with form -->

  <div class="pull-left submit">
    <%= f.submit "Create #{ @category_name } resource" %>
  </div>
  <% end %>
</div>

app/views/resources/show.html.erb
<% provide(:title, @category_name) %>
<div class="show-category">
<div class="category_names">
  <%= link_to @category_name, resources_path(:category => @category_id) %>
</div>
<table id="container">
  <tr class="top">
    <td class="photo">
      <% if @resource.photo != nil %>
      <%= image_tag(@resource.photo) %>
	  <% else %>
	  <%= image_tag("placeholder-image.jpg") %>
	  <% end %>
    </td>
    
<td class="align-bottom" width="27%">
<ul>
  <li><strong>Name:</strong>  <%= @resource.name %></li>
  <li><strong>Position:</strong>  <%= @resource.position %></li>
  <li><strong>Email:</strong>  <%= @resource.email %></li>
  </ul>
  </td>
<td class="align-bottom">
  <ul>
  <li><strong>Location:</strong>  <%= @resource.location %></li>
  <li><strong>Company:</strong>  <%= @resource.company %></li>
  <li><strong>Website:</strong>  <%= @resource.website %></li>
  </ul>
  </td>
</tr>

<tr>
<td colspan="3">
<%= render "shared/comment_form" %>
</td>
</tr>

<tr class="bottom">
  <% if @resource.comments.any? %>
  <td>
    <h4>Comments (<%= @num_comments %>)</h4>
 </td>
  <td>
    <h4>Average Rating: <%= @resource.average_rating %></h4>
  </td>
</tr>
<tr class="scroll-box">
<td colspan="3">
<ol>
<%= render @comments %>
</ol>
<% end %>
</td>
</tr>
</table>
</div>

app/views/shared/_comment_form.html.erb
<div class="comment-form">
<%= form_for([@resource, @resource.comments.build]) do |f| %>
  <div>
   <%= f.label :Rating %>
   <%= radio_button :comment, :rating, 1 %>
   <%= radio_button :comment, :rating, 2 %>
   <%= radio_button :comment, :rating, 3 %>
   <%= radio_button :comment, :rating, 4 %>
   <%= radio_button :comment, :rating, 5 %>
  </div>
  
  <div>
    <%= f.text_field :content, placeholder: "Add your comment here...",  class: 'form-control' %>
    </div>
  
  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="comment">
    <%= f.submit "Comment" %>
  </div>
  <% end %>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
</head>
<h1>Help Page</h1>
<p>This is help page, if you have any question, please go to 
    <a href="http://www.blueprinthealth.org/">BluePrint</a> 
    website.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<% if logged_in? %>
<div class="cat">
<ul class="categories">
  <% @categories.each do |category| %>
  <li>
    <div class="hexagon">
      <div class="link">
	<%= link_to resources_path(:category => category[1]) do %>
	    <%= image_tag("hexagon.png", class: "hex") %>
	    <%= image_tag("#{ category[0] }.png", class: "category-pix") %>
	    <div class="text">
	      <p><%= category[0] %></p>
	      </div>
      </div>
    <div class = "new_resource_link">
      <%= link_to new_resource_path(:category => category[1]) do %>
      <%= image_tag("plus.png", class: "plus") %>
      <% end %>
    </div>
    	<% end %>
	<% end %>
    </div>
  </li>
</ul>
</div>




<div class="newsfeed">
  <div class="inner">
    <% @comments.each do |comment| %>
    <% @resource = Resource.find_by(id: comment.resource_id) %>
    <% @category = @resource.category_id %>
    <div class="underline"><strong><%= Resource.names.key(@category) %></strong></div>
    <%= link_to @resource.name, @resource %> was reviewed by <%= comment.user.name %>
    <br />
    <%= comment.updated_at.to_date %>
    <br />
    <% end %>
    
    <!--<p class="underline">Legal</p>
    <p><span class="highlight">Adam Dinow at Wilson, Sonsini, Goodrich and Rosoti</span> was reviewed by <span class="highlight">Gil Addo from RubiconMD</span></p>
    <p class="underline">Accounting</p>
    <p><span class="higlight">Joshua Azran at Azran Financials</span> was reviewed by <span class="highlight">Samir Malik from iMedicare</span></p>
    <p class="underline">UI and UX Design</p>
    <p><span class="highlight">Elia Kanaki at Rossul</span> was reviewed by <span class="highlight">Matthew Loper from Wellth</span></p>
    <p class="underline">Marketing</p>
    <p><span class="highlight">Jacob Broude at Saotchi</span></p>-->
  </div>
</div>


<% else %>
<div class="homepage">
<div class="signup-button">
  <%= link_to "Get Started!", 'users/new' %>
</div>
</div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>

<div class="signin">
<div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

    <div class="form-field">
      <%= f.label :name,  "Full Name*" %>
      <%= f.text_field :name, :required => true,  class: 'form-control' %>
    </div>

    <div class="form-field">
      <%= f.label :email, "Email*" %>
      <%= f.email_field :email, :required => true,  class: 'form-control'  %>
    </div>

    <div class="form-field">
      <%= f.label :password, "Password*" %>
      <%= f.password_field :password, :required => true,  class: 'form-control'  %>
    </div>

     <div class="form-field">
       <%= f.label :password_confirmation,  "Password Confirmation*" %>
       <%= f.password_field :password_confirmation, :required => true,  class: 'form-control'  %>
    </div>

      <%= f.submit "Create My Account", class: "btn btn-primary" %>
    <% end %>
</div>
</div>

app/views/users/show.html.erb
<% provide(:title, 'Profile') %>
<div class="user">
  <p><strong>Name: </strong><%= @user.name %><p>
  <p><strong>Email: </strong><%= @user.email %></p>
  <p><%= link_to "Log out", logout_path, method: :delete %></p>

  <div class="user-comments">
  <ul>
  <% @comments.each do |comment| %>
  <li class="underline">
    <% @resource = Resource.find_by(id: comment.resource_id) %>
    <% @category = @resource.category_id %>
    <div>
    <%= Resource.names.key(@category) %>,  <%= link_to @resource.name, @resource %>
    </div>
    <div><%= comment.content %></div>
    <div>Rating: <%= comment.rating %> stars</div>
    </li>
  <% end %>
  </ul>
  </div>
  </div>